<a href="https://colab.research.google.com/github/Viratvenom/AIRBNB-EDA-PROJECT/blob/main/Artificial_Neural_Network_for_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing libraries**

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

tf.version

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.9/dist-packages/tensorflow/_api/v2/version/__init__.py'>

In [ ]:
# mount drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#read file
filepath = '/content/Copy of Folds5x2_pp.csv'
df = pd.read_csv(filepath)

 **Data PRE PROCESSING**

In [ ]:
df.head()

AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

In [ ]:
#importing dataset & pre-processing
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
print (x)
print (y)

[[   8.34   40.77 1010.84   90.01]
 [  23.64   58.49 1011.4    74.2 ]
 [  29.74   56.9  1007.15   41.91]
 ...
 [  15.99   43.34 1014.2    78.66]
 [  17.65   59.87 1018.58   94.65]
 [  23.68   51.3  1011.86   71.24]]
[480.48 445.75 438.76 ... 465.96 450.93 451.67]


In [ ]:
#spilting  the dataset test/training test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=0)

**Building ANN**

In [ ]:
#Initializing the ANN
from tensorflow import keras
ann = tf.keras.models.Sequential()

In [ ]:
#Adding the first layers
ann.add(tf.keras.layers.Dense(units=6, activation ='relu'))

In [ ]:
#Adding the seconds layer
ann.add(tf.keras.layers.Dense(units=6, activation ='relu'))

In [ ]:
#Adding the output layer
ann.add(tf.keras.layers.Dense(units=1))

**Training the Ann**

In [ ]:
#Compiling the ANN
ann.compile(optimizer= 'adam',loss = 'mean_squared_error')

In [ ]:
#Training the ANN model on the Training set
ann.fit(x_train , y_train ,batch_size = 32, epochs=100)

Epoch 1/100
240/240 [==============================] - 2s 2ms/step - loss: 596779.4375
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 128933.9688
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 9789.2432
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 130.3477
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 124.9444
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 122.8359
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 120.7024
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 118.4769
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 116.1646
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 113.5430
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 110.6818
Epoch 12/100
240/240 [==============================] - 0s 2ms/step

In [ ]:
#Predicting the results of the Test set
y_pred = ann.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 1ms/step
[[431.18 426.18]
 [450.59 451.1 ]
 [446.14 442.87]
 ...
 [457.15 454.2 ]
 [450.16 444.13]
 [432.43 436.58]]
