<a href="https://colab.research.google.com/github/Viratvenom/AIRBNB-EDA-PROJECT/blob/main/clustering_bank_customer_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing libraries**

In [40]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [41]:
tf.version

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.9/dist-packages/tensorflow/_api/v2/version/__init__.py'>

In [4]:
# mount drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [92]:
#read file
filepath = '/content/Churn_Modelling.csv'
df = pd.read_csv(filepath)

 **Data PRE PROCESSING**

In [93]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [94]:
# dataframe shape
df.shape

(10000, 14)

In [45]:
# unique values in each column
df.nunique()

RowNumber          10000
CustomerId         10000
Surname             2932
CreditScore          460
Geography              3
Gender                 2
Age                   70
Tenure                11
Balance             6382
NumOfProducts          4
HasCrCard              2
IsActiveMember         2
EstimatedSalary     9999
Exited                 2
dtype: int64

In [11]:
# Checking for duplicate records
df.duplicated().value_counts()

False    10000
dtype: int64

In [12]:
# Dataset Duplicate Value Count
print('Duplicate entries: {}'.format(df.duplicated().sum()))
print('{}% rows are duplicate.'.format(round((df.duplicated().sum()/df.shape[0])*100),2))
df.drop_duplicates(inplace = True)

Duplicate entries: 0
0% rows are duplicate.


In [46]:
# Visualizing the missing values
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [95]:
#importing dataset & pre-processing
x = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [96]:
print (x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [97]:
print (y)

[1 0 1 ... 1 1 0]


#Encoding Categorical Data

In [99]:
#Lable encoding 'Gender' column
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [100]:
print(x) # 0 :female 1:male

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#OneHot encoding Geograpy Column

In [101]:
#OneHot encoding Geograpy Column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# assuming that x is a 2D numpy array or pandas DataFrame with the Geography column as the second column
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = ct.fit_transform(x)  # x is transformed inplace and does not need to be assigned back to x


In [102]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [103]:
#spilting  the dataset test/training test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=0)

In [104]:
# Feature scaling
from sklearn.preprocessing import StandardScaler

# assuming that X is a 2D numpy array or pandas DataFrame with numerical features
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

**Building The ANN**

In [105]:
#Initializing the ANN
from tensorflow import keras
ann = tf.keras.models.Sequential()

In [106]:
#Adding the first layers# Recitifier neuralnetwork code
ann.add(tf.keras.layers.Dense(units=6, activation ='relu'))

In [107]:
#Adding the seconds layer
ann.add(tf.keras.layers.Dense(units=6, activation ='relu'))

In [108]:
#Adding the output layer
ann.add(tf.keras.layers.Dense(units=1,activation ='sigmoid'))

**Training the Ann**

In [109]:
#Compiling the ANN
ann.compile(optimizer= 'adam',loss = 'binary_crossentropy', metrics =['accuracy'] ) #mean_squared_error'

In [110]:
#Training the ANN model on the Training set
ann.fit(x_train , y_train ,batch_size = 32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6065 - accuracy: 0.7339
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4558 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4453 - accuracy: 0.7965
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4391 - accuracy: 0.7975
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4350 - accuracy: 0.7977
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4319 - accuracy: 0.8020
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4291 - accuracy: 0.8064
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4259 - accuracy: 0.8111
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4225 - accura

In [78]:
#Making the predictions  and evaluate the model

#customer leaving the bank
Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer?


In [116]:
# assuming that ann is a trained neural network model and scaler is a fitted scaler object
print(ann.predict(scaler.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
print(ann.predict(scaler.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5)


1/1 [==============================] - 0s 45ms/step
[[0.02]]
1/1 [==============================] - 0s 64ms/step
[[False]]


In [117]:
#Predicting the results of the Test set
y_pred = ann.predict(x_test)
y_pred = (y_pred>0.5)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


**Making the Confusion Matrix**

In [118]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print (cm)
accuracy_score(y_test, y_pred)

[[1518   77]
 [ 191  214]]


0.866